import "./globals.css";

export const metadata = {
  title: "TODO list",
  description: "Generated by Venkatesh"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
